const jsonData = require("./jsonData");
const testproblem1 = require("./test/testproblem1");
const testproblem2 = require("./test/testproblem2");
const testproblem3 = require("./test/testproblem3");
const testproblem4 = require("./test/testproblem4");
const testproblem5 = require("./test/testproblem5");
const testproblem6 = require("./test/testproblem6");
const testproblem7 = require("./test/testproblem7");
const testproblem8 = require("./test/testproblem8");
const testproblem9 = require("./test/testproblem9");
jsonData();
testproblem1();
testproblem2();
testproblem3();
testproblem4();
testproblem5();
testproblem6();
testproblem7();
testproblem8();
testproblem9();
